#!/usr/bin/env bash

# Focus/unfocus a window ("quake") with xdotool, wmctrl by binary name and plays an open/close mp3 file sound with ffmpeg
# Usage ./quake tilix /some/mp3file /some/other/mp3file
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <binary name> <mp3-open-file> <close-mp3-file>"
    exit 1
fi

if [! which xdotool >/dev/null 2>&1]; then
    echo "xdotool is required"
    exit 1
fi

if [! which wmctrl >/dev/null 2>&1]; then
    echo "wmctrl is required"
    exit 1
fi

if [! which ffplay >/dev/null 2>&1]; then
    echo "ffplay/ffmpeg is required"
    exit 1
fi

play_sound() {
    if [ ! -f $1 ]; then
        echo "File not found: $1"
        exit 1
    fi
    ffplay -nodisp -autoexit $1 >/dev/null 2>&1
}

name="$1"
pid="$(xdotool search --class "$name" getwindowpid || true)"

#  if no process is currently open, simply open with binary
if [ -z $pid ]; then
    nohup $name &>/dev/null &
    play_sound $2
    exit 0
fi

windowData="$(xdotool search --pid $pid | tail -1)"
windowData="$(wmctrl -l -p | grep $pid)"
windowId="${windowData:0:10}"

state="$(xprop -id $windowId | grep '_NET_WM_STATE(ATOM) = ')"

# hidden/minimized window
if [[ $state == *"_NET_WM_STATE_HIDDEN"* ]]; then
    eval $(xdotool getmouselocation --shell)
    xdotool windowmove $windowId $X $Y
    wmctrl -ir $wid -e 0,$X,$Y,"100%", "100%"
    xdotool windowactivate $windowId
    play_sound "$2"

else
    # not hidden
    xdotool windowminimize $windowId
    play_sound "$3"
fi
